# Generated by Django 2.2.12 on 2020-05-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200514_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='ghfhjgjhghg',
            new_name='hjghfjgh',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjhg',
        ),
    ]
