# Generated by Django 2.2.12 on 2020-05-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200514_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hghjg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjgj',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjgjg',
        ),
    ]
