# Generated by Django 2.2.12 on 2020-05-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200514_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='bbbgv',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='bgvhjv',
        ),
    ]
